# Generated by Django 3.0.3 on 2020-03-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSiteClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=20, null=True)),
                ('click', models.IntegerField()),
                ('advertisement', models.CharField(default='null', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('content', models.CharField(default='null', max_length=20)),
                ('country', models.CharField(default='null', max_length=10)),
                ('province', models.CharField(default='null', max_length=10)),
                ('city', models.CharField(default='null', max_length=10)),
                ('isp', models.CharField(default='null', max_length=10)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(default='null', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legendattach.WebSiteClick')),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Array',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('character', models.CharField(default='null', max_length=20)),
                ('servername', models.CharField(max_length=10)),
                ('gold', models.IntegerField()),
                ('machine', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=20)),
                ('website', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legendattach.WebSite')),
            ],
        ),
    ]
