# Generated by Django 3.0.3 on 2020-03-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legendattach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='array',
            name='website',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='legendattach.WebSite'),
        ),
    ]
