# Generated by Django 3.0.3 on 2020-03-22 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legendattach', '0002_auto_20200321_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='allip',
            name='advertisement',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='legendattach.WebSite'),
        ),
    ]
