# Generated by Django 3.0.3 on 2020-08-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendattach', '0006_auto_20200831_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='legendsite',
            name='onPage',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
