# Generated by Django 3.0.3 on 2020-08-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendattach', '0007_legendsite_onpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='legendsite',
            name='href',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
